#!/bin/bash

VERSION=0-1
PROGNAME=$(basename $BASH_SOURCE)

usage(){
    echo '${PROGNAME}  -f <head-file> [ -s <suffix> ] [ -i ] <file_list>'
    echo '${PROGNAME}  -b <header>    [ -s <suffix> ] [ -i ] <file_list>'
}

[ $# -eq 0 ] && usage && exit 0
[ "$1" == "-h" -o "$1" == "--help" ] && usage && exit 0

# parse input
# leading : suppress error message
head_type=0 # default from user
suffix='.head'
opts=$(getopt -o :b:f:his: --long help -n $PROGNAME -- "$@")
eval set -- "$opts"
while :; do
    case $1  in 
        f)
            headfile="$2"
            headtype=1
            [ ! -r "$headfile" ] && echo "Invalid head file \"$headfile\"" && \
                exit 1
            shift 2
            ;;
        b)
            headtype=0
            headtext="$2"
            shift 2
            ;;
        s)
            suffix="$2"
            shift 2
            ;;
        i)
            inplace=1
            shift 1
            ;;
        --) 
            shift
            break
            ;;
        *) # unrecognized option --show help
            echo "Invalid option: $1"  && usage && exit 1
            ;;
    esac
done
if [ filetype ]
