#!/bin/bash
mkdircd(){
    # "$@" is expanded to "$1" "$2" ...
    # which will further suffer to double quoted-expansion
    # first, \$ in "" literal $, so is \", then "\"\$$#\"" expands to
    #        "$2"
    # eval cd "$2"
    # so cd the last path created newly
    # 
    mkdir -p "$@" && eval cd "\"\$$#\""
}
