#!/bin/bash
syntax(){
    echo "Syntax:"
    echo "      pdf2png [-h] ifile ofile [600]"
    echo 
    echo "  Using gs to convert pdf file to png file. It expects three input parameters, "
    echo "first is necessary, other two are optional."
    echo 
    echo "Paramters:"
    echo "  ifile, input pdf file name"
    echo "  ofile, optional, output png file name, if not specified, it will be same as input file."
    echo "  res,   resolution(dpi), default is 600"
    echo 
    echo "Options:"
    echo "  -h, print this help"
}
if [ ! -x /usr/bin/gs ]; then echo "gs cannot be run.";exit 1;fi
if [ $# -gt 3 -o $# -lt 1 ]; then syntax;exit 1;fi
if [ "$1" = "-h" ]; then syntax;exit 0;fi
ifile="${1%.pdf}.pdf"
ofile="${2:-${1%.pdf}}"
res=${3:-600}
ofile="${ofile%.png}.png"
if [ ! -f "${ifile}" ]; then echo "File $ifile doesnot exist."; exit 1;fi
#if [ -f "${ofile}" ]; then echo "File $ofile exists. Please give a new name.";exit 1; fi
gs -o -q -sDEVICE=png256 -dPDFCrop -r${res} -o${ofile} ${ifile} >/dev/null
