#!/bin/bash
VERSION="0-1"
PROGNAME=$(basename $0)

usage(){
    echo "SYNOPSIS:"
    echo "  ${PROGNAME} n <string>"
    echo ""
    echo "Example:"
    echo ""
    echo "      ${PROGNAME} 10 a"
}
strrepeat0(){
#for repeat a string, special for those without IFS in it
    local n=$1
    local str="$2"
    local output
    local i
    for((i=0;i<n;++i)) do
        output="${output}$2"
    done
    echo "${output}"
}
[ $# -eq 0 ] && usage && exit 0
[ "$1" == "-h" -o "$1" == "${--help}" ] && usage && exit 0
if ! isnumber "$1"; then
    echo "First parameter must be a number." && exit 1
fi
strrepeat0 "$1"  "$2"
